source 'https://rubygems.org'

gem 'rails', '4.1.1'

gem 'rails-api'

gem 'spring', :group => :development

gem 'sqlite3'

gem "active_model_serializers", "~> 0.8.0"


# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
gem 'debugger', :group => :development

gem 'redis'

gem 'devise'
