# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b1b0abb4f388a7a0c5dead56e1ab7b4f97712c45bd446167d194ba4ed0fdf4f8b09aaf3fa2700cf1f24617a01d8df5e362984f73eab38af79401d9fee02ff85

test:
  secret_key_base: dead8932c5b2eda076e83dd142b634a626132430c5a633dadabf871c30be7706d28dbd879d0b25b49ef662faba906eb84342e3bf766f66fd108a61095a755234

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
